# Python Tutorial: Python Numpy

By: jcchouinard.com

-----


## np.arange()

In [1]:
import numpy as np 

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(2,15,1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
np.arange(2,16,2)

array([ 2,  4,  6,  8, 10, 12, 14])

## Conclusion

Help me and subscribe to this channel.

Stay tuned for my upcoming Python for SEO course.

### [jcchouinard.com](https://www.jcchouinard.com/)
### [youtube.com/@jcchouinard](https://www.youtube.com/@jcchouinard)
### [twitter.com/ChouinardJC](https://twitter.com/ChouinardJC)
### [linkedin.com/in/jeanchristophechouinard](https://www.linkedin.com/in/jeanchristophechouinard)
